sperimentazioni1: sperimentazioni1_main.o sperimentazioni1_funzioni.o
	gcc -o sperimentazioni1 sperimentazioni1_main.o sperimentazioni1_funzioni.o
sperimentazioni1_main.o: sperimentazioni1_main.c sperimentazioni1_header.h
	gcc -c sperimentazioni1_main.c
sperimentazioni1_funzioni.o: sperimentazioni1_funzioni.c sperimentazioni1_header.h
	gcc -c sperimentazioni1_funzioni.c